environment:
  path_to_sln: src/DotNet.Cabinets.sln
skip_tags: true
image: Visual Studio 2019
#assembly_info:
#  patch: false
install:
  - cmd: choco install gitversion.portable -pre -y
  #- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  #- cmd: appveyor-tools\secure-file -decrypt dazinator.snk.enc -secret %signingkey%

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: minimal
build_script:
- cmd: dotnet restore %path_to_sln% /p:PackageVersion=%GitVersion_FullSemVer%
- cmd: dotnet build %path_to_sln% -c Release /p:PackageVersion=%GitVersion_FullSemVer%
- cmd: dotnet pack %path_to_sln% -c Release /p:PackageVersion=%GitVersion_FullSemVer%
test_script:
- cmd: dotnet test src/DotNet.Cabinet.Tests/DotNet.Cabinets.Tests.csproj
artifacts:
- path: /src/**/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: fv0AzEtZznVqb3V1d5JaR62XK5eQuyySgBP2J54HqFQXM01jMqKXHiLOOIdVsa9H
  skip_symbols: false
  artifact: /.*\.nupkg/