  # environment variables
environment:
  path_to_sln: src/DotNet.Cabinets.sln 
skip_tags: true
install:
  - choco install gitversion.portable -pre -y 
image: Visual Studio 2017 
assembly_info:
  patch: false
before_build:
- ps: gitversion /l console /output buildserver
- cmd: msbuild %path_to_sln% /t:restore /p:PackageVersion=%GitVersion_NuGetVersion%
build:
  project: '%path_to_sln%'
  verbosity: minimal
after_build:
- cmd: msbuild %path_to_sln% /t:Pack /p:PackageVersion=%GitVersion_NuGetVersion%
artifacts:
- path: /src/**/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  skip_symbols: false
  artifact: /.*\.nupkg/