name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/DotNet.Cabinets.sln
    - name: Build
      run: dotnet build --no-restore src/DotNet.Cabinets.sln
    - name: Test
      run: dotnet test src/DotNet.Cabinets.Tests.csproj --no-build --verbosity normal
    
